# Generated by Django 5.2.13 on 2026-06-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vendors',
            new_name='Vendeur',
        ),
    ]
